import Head from 'next/head'
import Image from 'next/image'
import Style from 'styles/Index.module.scss';

export default function Home() {
    return (
        <div className={Style.Main}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <div className={Style.logo}>NWTF</div>
                <ul>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Courses</a>
                    </li>
                    <li>
                        <a href="#">Features</a>
                    </li>
                    <li>
                        <a href="#">Pricing</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                </ul>
            </header>

            <section className={Style.main}>
                <div className={Style.heading}>
                    <h1>Master skills that you can use</h1>
                    <h2>Learn techincal skills that are relevant to current industries.</h2>
                </div>
            </section>
        </div>
    )
}
